#!/bin/sh

if [ -z "$1" -o -z "$2" ]; then
  echo "usage: $(basename $0) <directory> <diff-extension>" 1>&2
  exit 1
fi

: ${DIFF:=diff}
: ${GENDIFF_DIFF_ARGS:=-up}
: ${GENDIFF_DIFF_CHANGELOG_ARGS:=-U0}

find $1 \( -name "*$2" -o -name ".*$2" \) -print | sort |
while read f; do
    U="${GENDIFF_DIFF_ARGS}"
    [ "`basename $f`" = "ChangeLog$2" ] && U="${GENDIFF_DIFF_CHANGELOG_ARGS}"
    diffcmd="${DIFF} ${U} /dev/null ${f%$2}"
    # ${DIFF} ${U} $f `echo $f | sed s/$2\$//`
    [ -r "$f" ] && diffcmd="${DIFF} ${U} ${f} ${f%$2}"
    echo "${diffcmd}"
    ${diffcmd}
done
